# ----- Data -----
data:
  repo_id: "TornikeO/era5-5.625deg"
  local_dir: "./dataset/era5_data"
  data_paths: [
    "./dataset/era5_data/geopotential_500/*.nc",
    "./dataset/era5_data/temperature_850/*.nc",
    "./dataset/era5_data/2m_temperature/*.nc",
    "./dataset/era5_data/10m_u_component_of_wind/*.nc",
    "./dataset/era5_data/10m_v_component_of_wind/*.nc",
  ]
  levels: ["z", "t", "t2m", "u10", "v10"]        
  time:
    train_start: "2010-01-01"
    train_end:   "2014-12-31"
    val_start:   "2015-01-01"
    val_end:     "2016-12-31"
    test_start:  "2017-01-01"
    test_end:    "2018-12-31"
  sample_rate: "6-hourly"        # daily, hourly or 6-hourly
  wind_u_key: "u10"              # added: identifies U-component channel
  wind_v_key: "v10"              # added: identifies V-component channel

# ----- Training -----
training:
  batch_size: 1
  num_workers: 0
  epochs: 20
  early_stopping: 3
  learning_rate: 0.001
  weight_decay: 1e-5

  lambda_ke: 0.01                # weight for kinetic energy loss
  ke_mode: "pointwise"           # options: "pointwise", "global", or "both"
  ke_use_truth: true             # toggles what we're comparing our pred_ke to
  ke_compare_to_last_input: false  # only "true" if we want to conserve ke from the previous timestep, as opposed to...
                                   # the current ground truth (when ke_use_truth == true, ke_compare_to_last_input is
                                   # always false, and vice versa)


# ----- Spatio-Temporal Graph -----
graph:
  input_length: 7
  forecast_horizon: 1
  neighborhood: 4            # 4 or 8
  type: "strong"             # strong or cartesian             