name: weather-cast
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pyyaml
  - tqdm
  - xarray
  - netcdf4
  - h5py
  - h5netcdf
  - pyg-lib
  - torch-geometric
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  - huggingface_hub
  - joblib
  - ipykernel
  - dask
  - pip
  - pip:
    - torch-spatiotemporal
