graph_based:
  gtcnn:
    hidden_channels: 64
    chebyshev_order: 1        
    num_layers: 3
    dropout: 0.1
  scalable_gtcnn:
    hidden_channels: 64
    chebyshev_order: 3        
    num_layers: 3
    dropout: 0.1
    num_neighbors: [25, 10, 5]  # 3-hop sampling to match 3-layer GTCNN
    neighborhood: 4
    sampling_strategy: "single"

grid_based:
  cnn3d:
    hidden_channels: [32, 64]
    kernel_size: [3, 3, 3]
    dropout: 0.1

  convlstm:
